sudo: true
dist: trusty
language: ruby
rvm:
  - 2.3

services:
  - docker

jobs:
  include:
    - stage: build docker image
      if: type IN (pull_request)
      install: true
      script:
      - docker build -t microsoft/terraform-test:$TERRAFORM_VERSION --build-arg tfver=$TERRAFORM_VERSION --build-arg gover=$GOLANG_VERSION .
